In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
import keras
from keras.datasets import mnist
from keras.models import Sequential
from keras.layers import Dense, Dropout
test_size=0.1
batch_size = 1024
epochs = 20

In [2]:
data = pd.read_csv('gene_expression_regression.csv')
data_array=data.iloc[:,1:].values
X = data_array[:,:943]
Y = data_array[:,-1]

In [3]:
x_train, x_test, y_train, y_test = train_test_split(X, Y, test_size=test_size)

In [4]:
model = Sequential()
model.add(Dense(512, activation='relu', input_shape=(X.shape[1],)))
model.add(Dropout(0.2))
model.add(Dense(512, activation='relu'))
model.add(Dropout(0.2))
model.add(Dense(1, activation='tanh'))

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [5]:
model.summary()

model.compile(loss='mean_squared_error',
              optimizer=keras.optimizers.Adam(),
              metrics=['mae'])

history = model.fit(x_train, y_train,
                    batch_size=batch_size,
                    epochs=epochs,
                    verbose=1,
                    validation_data=(x_test, y_test))
score = model.evaluate(x_test, y_test, verbose=0)
print('Test loss:', score[0])
print('Test accuracy:', score[1])

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 512)            │       483,328 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout (Dropout)               │ (None, 512)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 512)            │       262,656 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_1 (Dropout)             │ (None, 512)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │           513 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 746,497 (2.85 MB)

 Trainable params: 746,497 (2.85 MB)

 Non-trainable params: 0 (0.00 B)

Epoch 1/20
114/114 ━━━━━━━━━━━━━━━━━━━━ 15s 118ms/step - loss: 0.4217 - mae: 0.4680 - val_loss: 0.2085 - val_mae: 0.3237
Epoch 2/20
114/114 ━━━━━━━━━━━━━━━━━━━━ 19s 107ms/step - loss: 0.2085 - mae: 0.3257 - val_loss: 0.1897 - val_mae: 0.3069
Epoch 3/20
114/114 ━━━━━━━━━━━━━━━━━━━━ 20s 103ms/step - loss: 0.1804 - mae: 0.3026 - val_loss: 0.1776 - val_mae: 0.2976
Epoch 4/20
114/114 ━━━━━━━━━━━━━━━━━━━━ 21s 108ms/step - loss: 0.1695 - mae: 0.2914 - val_loss: 0.1710 - val_mae: 0.2903
Epoch 5/20
114/114 ━━━━━━━━━━━━━━━━━━━━ 12s 106ms/step - loss: 0.1612 - mae: 0.2833 - val_loss: 0.1674 - val_mae: 0.2856
Epoch 6/20
114/114 ━━━━━━━━━━━━━━━━━━━━ 12s 108ms/step - loss: 0.1547 - mae: 0.2769 - val_loss: 0.1645 - val_mae: 0.2821
Epoch 7/20
114/114 ━━━━━━━━━━━━━━━━━━━━ 20s 105ms/step - loss: 0.1476 - mae: 0.2696 - val_loss: 0.1624 - val_mae: 0.2804
Epoch 8/20
114/114 ━━━━━━━━━━━━━━━━━━━━ 20s 102ms/step - loss: 0.1453 - mae: 0.2663 - val_loss: 0.1622 - val_mae: 0.2793
Epoch 9/20
114/114 ━━━━━━━━━━━━━

In [6]:
y_pred=model.predict(x_test)

404/404 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step


In [7]:
y_test

array([-1.0224923 ,  0.73116845,  1.1048353 , ...,  0.5365888 ,
       -0.57343745, -0.9155196 ])

In [8]:
np.corrcoef(y_test.flatten(), y_pred.flatten())

array([[1.        , 0.93836767],
       [0.93836767, 1.        ]])

# Baseline linear regression model result

In [9]:
from sklearn.linear_model import LinearRegression

In [10]:
reg = LinearRegression()
reg.fit(x_train, y_train)

LinearRegression()

In [11]:
np.corrcoef(reg.predict(x_test).flatten(), y_test)

array([[1.        , 0.89702055],
       [0.89702055, 1.        ]])